config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'articles/index'

  get 'welcome/index'

  root to: 'globals#index'

  resources :categories, shallow: true do
      resources :apps do
          resources :images
          resources :pros
          resources :cons
          resources :top10s
      end
  end

 

  resources :stores do
    resources :countries do
    end
  end

get 'admins' => 'admins#index'

get 'top10s' => 'top10s#index'
get 'global' => 'globals#index'
get 'articles/set/:page' => 'articles#paginateMainPage', :page => /\d+/
get 'articles/search/:name' => 'articles#searchArticles'
get 'articles/search/:name/set/:page' => 'articles#searchPaginateArticles'
get 'categories/:name/articles' => 'articles#showArticlesByCat'
get 'categories/:name/articles/set/:page' => 'articles#showPaginateArticlesByCat'
get 'articles/:name' => 'articles#show'
  

end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :top10s, dependent: :destroy
  has_many :pros, dependent: :destroy
  has_many :cons, dependent: :destroy
  validates :name, :description, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :apps
	validates :name, presence: true

end

app/models/con.rb
class Con < ActiveRecord::Base
  belongs_to :app
  #has_and_belongs_to_many :apps
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :store
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :app

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/pro.rb
class Pro < ActiveRecord::Base
  belongs_to :app
  #has_and_belongs_to_many :apps
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :countries
	validates :label, presence: true
end

app/models/top10.rb
class Top10 < ActiveRecord::Base
  belongs_to :app
  #has_many :apps
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/top10s_controller.rb
class Top10sController < ApplicationController

	def new
		@app = App.find(params[:app_id])
		@top10 = @app.top10s.new  
  	end

  	def create
		
    	@app = App.find(params[:app_id])
    	@top10 = @app.top10s.create(top10_params)
    	redirect_to edit_app_path(@app)
  	end

  	def index 
  		@top10s = App.joins(:top10s).select("top10S.id", :name, :rank ).where(released: true).order("rank")
  	end

  	def destroy
  		@top10 = Top10.find(params[:id])
  		@top10.destroy

  		redirect_to app_path(@top10.app_id)
  	end

  	def edit
  		@top10 = Top10.find(params[:id])
  	end

  	def update
  		@top10 = Top10.find(params[:id])
   		if @top10.update(top10_params)
   		   	redirect_to app_path(@top10.app_id)
    	else
      		render 'edit'
    	end
  	end

  	def show
  		#@category = Category.find(params[:category_id])
    	@app = App.find(params[:id])
    	#@top10 = @app.top10s.build
  	end

  	  private
    def top10_params
      params.require(:top10).permit(:rank)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cons_helper.rb
module ConsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pros_helper.rb
module ProsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/top10s_helper.rb
module Top10sHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/top10s/_form.html.erb
<%= form_for([@app, @app.top10s.build]) do |f|%>

	<% if @app.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@app.errors.count, "error")%> prohibited this app for being saved:
			</h2>
			<ul>
				<% @app.errors.full_messages.each do |msg| %>
					<li><%= msg%></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="row">
		<div class="large-5 large-offset-2 columns">
			<%= f.label :rank%>
			<%= f.number_field :rank %>

			<div class="button secondary">
				<%= f.submit%>
			</div>
		</div>
	</div>
<%end%>

app/views/top10s/_form_edit.html.erb
<%= form_for @top10 do |f|%>

<% if @top10.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@top10.errors.count, "error")%> prohibited this top10 for being saved:
		</h2>
		<ul>
			<% @top10.errors.full_messages.each do |msg| %>
			<li><%= msg%></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="row">
		<div class="large-5 large-offset-2 columns">
			<%= f.label :rank%>
			<%= f.number_field :rank %>
	
		 	<div class="button secondary">
				<%= f.submit%>
			</div>
		</div>
	</div>		
<%end%>

app/views/top10s/_top10.html.erb
<tr>
		<td><%= top10.rank%></td>
		<td><%= link_to 'edit', edit_top10_path(top10)%></td>
		<td><%= link_to 'destroy', [top10], method: :delete, data: { confirm:"sure?"}%></td>
	</tr>

app/views/top10s/edit.html.erb
<div class="row">
	<div class="large-1 columns">
		<div class="button secondary">
			<%= link_to 'back', app_path(@top10.app_id) %>
		</div>
	</div>
	<div class="large-10 columns">
		<h1>Editing top10 for application</h1>
	</div>
</div>

<%= render 'form_edit'%>

app/views/top10s/index.html.erb
<div class="row">
	<div class="large-1 columns">
		<div class="button secondary">
			<%= link_to 'back', admins_path %>
		</div>
	</div>
	<div class="large-10 columns">
		<h1>All Top 10</h1>
	</div>
</div>
<div class="row">
	<div class="large-5 large-offset-2 columns">
		<table>
			<tr>
				<th>Rank</th>
				<th>Application</th>
				<th colspan="3"></th>
			</tr>
			<%  @top10s.each do |top10| %>

				<tr>
					<td><%= top10.rank%></td>
					<td><%= top10.name%></td>
					<td><%= link_to 'edit', edit_top10_path(top10)%></td>
					<td><%= link_to 'destroy', top10_path(top10.id), method: :delete, data: { confirm:"sure?"}%></td>
				</tr>

			<%end%>
		</table>
	</div>
</div>

app/views/top10s/new.html.erb
<h2>New top10</h2>
<%= render 'form' %>

app/views/top10s/show.html.erb
<p>
	<strong>rank:</strong>
	<%= @top10.rank %>
</p>