config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'articles/index'

  get 'welcome/index'

  root to: 'globals#index'

  resources :categories, shallow: true do
      resources :apps do
          resources :images
          resources :pros
          resources :cons
          resources :top10s
      end
  end

 

  resources :stores do
    resources :countries do
    end
  end

get 'admins' => 'admins#index'

get 'top10s' => 'top10s#index'
get 'global' => 'globals#index'
get 'articles/set/:page' => 'articles#paginateMainPage', :page => /\d+/
get 'articles/search/:name' => 'articles#searchArticles'
get 'articles/search/:name/set/:page' => 'articles#searchPaginateArticles'
get 'categories/:name/articles' => 'articles#showArticlesByCat'
get 'categories/:name/articles/set/:page' => 'articles#showPaginateArticlesByCat'
get 'articles/:name' => 'articles#show'
  

end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :top10s, dependent: :destroy
  has_many :pros, dependent: :destroy
  has_many :cons, dependent: :destroy
  validates :name, :description, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :apps
	validates :name, presence: true

end

app/models/con.rb
class Con < ActiveRecord::Base
  belongs_to :app
  #has_and_belongs_to_many :apps
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :store
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :app

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/pro.rb
class Pro < ActiveRecord::Base
  belongs_to :app
  #has_and_belongs_to_many :apps
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :countries
	validates :label, presence: true
end

app/models/top10.rb
class Top10 < ActiveRecord::Base
  belongs_to :app
  #has_many :apps
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cons_helper.rb
module ConsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pros_helper.rb
module ProsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/top10s_helper.rb
module Top10sHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/index.html.erb
<div class="row">
	<div class="large-12  columns">
		<h1>Iphone-App-World Administation pages</h1>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<div class="button secondary">
			<%= link_to 'Show & edit categories', controller: 'categories'%>
		</div>
		<div class="button secondary">
			<%= link_to 'Show top 10', controller: 'top10s'%>
		</div>
	</div>
</div>

app/views/apps/_app.html.erb
<tr>
		<td><%= app.name%></td>
		<td><%= link_to 'show', [app]%></td>
		<td><%= link_to 'edit', edit_app_path(app)%></td>
		<td><%= link_to 'destroy', [app], method: :delete, data: { confirm:"sure?"}%></td>
	</tr>

app/views/apps/_form.html.erb
<%= form_for ([@category, @category.apps.build]) do |f|%>
	<div class="row">
		<div class="large-5 large-offset-2 columns">
			<%= f.label :name%>
			<%= f.text_field :name %>
		
			<%= f.label :url%>
			<%= f.text_field :url%>
		
			<%= f.label :price%>
			<%= f.number_field :price%>
		
			<%= f.label :Description%>
			<%= f.text_area :description%>
		
			<%= f.label :analysis%>
			<%= f.text_area :analysis%>

			<%= f.submit%>
		</div>
	</div>

	<%end%>

app/views/apps/_form_edit.html.erb
<%= form_for @app do |f|%>
	<div class="row">
		<div class="large-5 columns">
			<%= f.label :name%>
			<%= f.text_field :name %>

			<%= f.label :url%>
			<%= f.text_field :url%>

			<%= f.label :price%>
			<%= f.number_field :price%>

			<%= f.label :Description%>
			<%= f.text_area :description%>

			<%= f.label :analysis%>
			<%= f.text_area :analysis%>

			<%= f.submit%>
		</div>
	
		<div class="large-5 columns">
			<h2>Listed pros</h2>
			<div class="button secondary">
				<%= link_to 'New pro', new_app_pro_path(@app)%>
			</div>
			<table>
				<tr>
					<th>description</th>
					<th colspan="2"></th>
				</tr>
				<%= render @app.pros%>
			</table>

			<h2>Listed cons</h2>
			<div class="button secondary">
				<%= link_to 'New con', new_app_con_path(@app)%>
			</div>
			<table>
				<tr>
					<th>description</th>
					<th colspan="2"></th>
				</tr>
				<%= render @app.cons%>
			</table>

			<!-- SHOW top10-->
			<h2>Top 10</h2>
			<% if @app.top10s.any? %>
				<table>
					<tr>
						<th>rank</th>
						<th colspan="2"></th>
					</tr>
					<%= render @app.top10s %>
				</table>
			<% else %>
				<div class="button secondary">
					<%= link_to 'New in Top 10', new_app_top10_path(@app)%>
				</div>
			<% end %>
			
			<!-- show image-->
			<h2>Images</h2>
			<%= render @app.images %>

			<h6>Add new image</h6>
			<%= render 'images/form' %>
		</div>
	</div>

<%end%>

app/views/apps/edit.html.erb
<div class="row">
	<div class="large-9 large-offset-3 columns">
		<h1>Editing application <%= @app.name.capitalize %></h1>
	</div>
</div>

<div class="row">
	<div class="large-1 columns">
		<div class="button secondary">
			<%= link_to 'back', app_path %>
		</div>
	</div>
</div>
	
<%= render 'form_edit'%>

app/views/apps/new.html.erb
<div class="row">
	<div class="large-10 large-offset-2 columns">
		<h1>New Application for <%= @category.name.capitalize %></h1>
	</div>
</div>
<div class="row">
	<div class="large-3 columns">
		<div class="button secondary">
			<%= link_to 'Back to categories index', categories_path %>
		</div>
	</div>
</div>


<%= render 'form'%>

app/views/apps/show.html.erb
<div class="row">
	<div class="large-9 large-offset-3 columns">
		<h1>Application <%= @app.name.capitalize %></h1>
	</div>
</div>
<div class="row">
	<div class="large-3 columns">
		<div class="button secondary">
			<%= link_to 'back', category_path(@app.category_id)%>
		</div>
	</div>
</div>

<div class="row">
	<div class="large-6 columns">
		<strong>Name:</strong>
		<%= @app.name %><br>

		<strong>url:</strong>
		<%= @app.url %><br>

		<strong>price:</strong>
		<%= @app.price %><br>

		<strong>description:</strong>
		<%= @app.description %><br>

		<strong>analysis:</strong>
		<%= @app.analysis %><br>

		<div class="button secondary">
			<%= link_to 'edit', edit_app_path(@app)%>
		</div>
	</div>


	<div class="large-6 columns">
		<!-- SHOWPros -->
		<h2>Listed pros</h2>
		<table>
			<tr>
				<th>description</th>
				<th colspan="2"></th>
			</tr>
		<%= render @app.pros%>
		</table>

		<!-- SHOW Cons-->
		<h2>Listed cons</h2>
		<table>
			<tr>
				<th>description</th>
				<th colspan="2"></th>
			</tr>
		<%= render @app.cons%>
		</table

		<!-- SHOW top10-->
		<h2>Top 10</h2>
		<% if @app.top10s.any? %>
			<table>
				<tr>
					<th>rank</th>
					<th colspan="2"></th>
				</tr>
				<%= render @app.top10s %>
			</table>
		<% else %>
			<div class="button secondary">
				<%= link_to 'New in Top 10', new_app_top10_path(@app)%>
			</div>
		<% end %>

		<!-- show images -->
		<h2>Images</h2>
		<%= render @app.images %>

		<h6>Add new image</h6>
		<%= render 'images/form' %>
	</div>
</div>