config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'articles/index'

  get 'welcome/index'

  root to: 'globals#index'

  resources :categories, shallow: true do
      resources :apps do
          resources :images
          resources :pros
          resources :cons
          resources :top10s
      end
  end

 

  resources :stores do
    resources :countries do
    end
  end

get 'admins' => 'admins#index'

get 'top10s' => 'top10s#index'
get 'global' => 'globals#index'
get 'articles/set/:page' => 'articles#paginateMainPage', :page => /\d+/
get 'articles/search/:name' => 'articles#searchArticles'
get 'articles/search/:name/set/:page' => 'articles#searchPaginateArticles'
get 'categories/:name/articles' => 'articles#showArticlesByCat'
get 'categories/:name/articles/set/:page' => 'articles#showPaginateArticlesByCat'
get 'articles/:name' => 'articles#show'
  

end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :top10s, dependent: :destroy
  has_many :pros, dependent: :destroy
  has_many :cons, dependent: :destroy
  validates :name, :description, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :apps
	validates :name, presence: true

end

app/models/con.rb
class Con < ActiveRecord::Base
  belongs_to :app
  #has_and_belongs_to_many :apps
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :store
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :app

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/pro.rb
class Pro < ActiveRecord::Base
  belongs_to :app
  #has_and_belongs_to_many :apps
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :countries
	validates :label, presence: true
end

app/models/top10.rb
class Top10 < ActiveRecord::Base
  belongs_to :app
  #has_many :apps
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < AdminsController
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if(@category.save)
       redirect_to categories_path
    else
      render 'new'
    end
    render plain: params[:category].inspect
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def index
    @categories = Category.all
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cons_helper.rb
module ConsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pros_helper.rb
module ProsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/top10s_helper.rb
module Top10sHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do|f|%>

	<% if @category.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@category.errors.count, "error")%> prohibited this category for being saved:
			</h2>
			<ul>
				<% @category.errors.full_messages.each do |msg| %>
				<li><%= msg%></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="row">
		<div class="large-5 large-offset-2 columns">
			<%= f.label :name %>
			<%= f.text_field :name %><br>
			<%= f.submit%>
		</div>
	</div>

<% end %>

app/views/categories/create.html.erb
<div class="row">
	<div class="large-9 large-offset-2 columns">
		<h1>Create new category</h1>
	</div>
</div>

app/views/categories/edit.html.erb
<div class="row">
	<div class="large-1 columns">
		<div class="button secondary">
			<%= link_to 'back', category_path %>
		</div>
	</div>
	
	<div class="large-7 large-offset-2 columns">
		<h1>Editing category <%= @category.name.capitalize %></h1>
	</div>
</div>


<%= render 'form'%>

app/views/categories/index.html.erb
<div class="row">
	<div class="large-9 large-offset-3 columns">
		<h1>Categories listing</h1>
	</div>
</div>

<div class="row">
	<div class="large-3 columns">
		<div class="button secondary">
			<%= link_to 'back', controller:'admins' %>
		</div>
	</div>
	<div class="large-3 columns">
		<div class="button secondary">
			<%= link_to 'new category', new_category_path %>
		</div>
	</div>
</div>

<div class="row">
	<div class="large-9 large-offset-3 columns">
		<table>
			<tr>
				<th>Category name</th>
				<th colspan="3"></th>
			</tr>

			<% @categories.each do |category| %>
				<tr>
					<td><%= category.name%></td>
					<td><%= link_to 'show', category_path(category)%></td>
					<td><%= link_to 'edit', edit_category_path(category)%></td>
					<td><%= link_to 'destroy', category_path(category), method: :delete, data: { confirm:"sure?"}%></td>
				</tr>
			<%end%>
		</table>
	</div>
</div>

app/views/categories/new.html.erb
<div class="row">
	<div class="large-9 large-offset-3 columns">
		<h1>New category</h1>
	</div>
</div>

<%= render 'form'%>

<div class="row">
	<div class="large-3 columns">
		<div class="button secondary">
			<%= link_to 'back', categories_path %>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<div class="row">
	<div class="large-9 large-offset-3 columns">
		<h1>Articles for <%= @category.name.capitalize %></h1>
	</div>
</div>

<div class="row">
	<div class="large-3 columns">
		<div class="button secondary">
			<%= link_to 'Back to category listing', categories_path%>
		</div>
	</div>
	<div class="large-3 columns">
		<div class="button secondary">
			<%= link_to 'Edit category', edit_category_path(@category)%>
		</div>
	</div>
</div>
<!-- SHOWArticles -->
<div class="row">
	<div class="large-5 large-offset-4 columns">
		<h2>Application Listing</h2>
		<table>
			<tr>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
			<%= render @category.apps%>
		</table>
	</div>
	<div class="large-3 columns">
		<div class="button secondary">
			<%= link_to 'New application', new_category_app_path(@category)%>
		</div>
	</div>
</div>



<!--ADDArticles-->


<!-- %= render 'apps/form'%> -->


<!-- links -->